GET http://localhost:3000/orders/019c9c9d-ff28-7782-9198-9a6d1bb0bc5d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NzIxNTc0NjcsImV4cCI6MTc3NDc0OTQ2NywiYXVkIjoiZGVzYWZpby1hcGkiLCJpc3MiOiJkZXNhZmlvLWFwaSIsInN1YiI6IjAxOWM5YzhmLTY2Y2YtNzJlZS1iZjk5LTBlMTNkNTZhNGNkMCJ9.dQJs_F9YZVfCFdcOQPuB3DPahnXco2obvyn56pwdQUI